[package]
name = "d5-p2-cafeteria"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
log = "0.4.29"
aoc25 = { path = "../aoc25" }
indicatif = "0.18.3"
itertools = "0.14.0"
clap = { version = "4.5.53", features = ["derive"] }
